### PR TITLE
Husky + commits from #49

### PR DESCRIPTION
**Pull request by Valexr**

### CODE REVIEW

**Review by blokhin — APPROVED** [review]

**Comment by blokhin** [comment]
@valexr are you sure the new formatting options are correct and coherent with the existing code style?

**Comment by Valexr** [comment]
> @Valexr are you sure the new formatting options are correct and coherent with the existing code style?

What’s new formatting options?

**Comment by blokhin** [comment]
@Valexr here: https://github.com/basf/bscience-gui/blob/master/.editorconfig

**Comment by Valexr** [comment]
> @Valexr here: https://github.com/basf/bscience-gui/blob/master/.editorconfig (cf. `prettier`)

If this setting wasn't coherent more code would be changed in PR - because husky run formatting code on each commit.

**Pull request merged**
